Repository Bumblebee-Bee/XChangePass, pull requests merged in 2025-04, with the labels that each got.

#83 Feature/jira kan 69 카드 결제 성능 체크
  .gitignore
  build.gradle
  docker-compose.yml
  k6-scripts/cardFunctions.js
  k6-scripts/userFunctions.js
  src/main/java/bumblebee/xchangepass/domain/card/controller/CardPaymentController.java
  src/main/java/bumblebee/xchangepass/domain/card/dto/request/PaymentRequest.java
  src/main/java/bumblebee/xchangepass/domain/card/dto/response/BasicCardInfoResponse.java
  src/main/java/bumblebee/xchangepass/domain/card/dto/response/DetailedCardInfoResponse.java
  src/main/java/bumblebee/xchangepass/domain/card/dto/response/PaymentResponse.java
  src/main/java/bumblebee/xchangepass/domain/card/service/CardPaymentService.java
  src/main/java/bumblebee/xchangepass/domain/card/service/CardService.java
  src/main/java/bumblebee/xchangepass/domain/cardTransaction/controller/CardTransactionController.java
  src/main/java/bumblebee/xchangepass/domain/cardTransaction/dto/request/PaymentApprovedEvent.java
  src/main/java/bumblebee/xchangepass/domain/cardTransaction/dto/response/CardTransactionDetailResponse.java
  src/main/java/bumblebee/xchangepass/domain/cardTransaction/dto/response/CardTransactionSummaryResponse.java
  src/main/java/bumblebee/xchangepass/domain/cardTransaction/entity/CardTransaction.java
  src/main/java/bumblebee/xchangepass/domain/cardTransaction/entity/TransactionType.java
  src/main/java/bumblebee/xchangepass/domain/cardTransaction/repository/CardTransactionRepository.java
  src/main/java/bumblebee/xchangepass/domain/cardTransaction/repository/CardTransactionRepositoryCustom.java
  src/main/java/bumblebee/xchangepass/domain/cardTransaction/repository/CardTransactionRepositoryImpl.java
  src/main/java/bumblebee/xchangepass/domain/cardTransaction/service/CardTransactionService.java
  src/main/java/bumblebee/xchangepass/domain/user/entity/User.java
  src/main/java/bumblebee/xchangepass/domain/user/repository/UserRepository.java
  src/main/java/bumblebee/xchangepass/global/common/CursorResponse.java
  src/main/java/bumblebee/xchangepass/global/error/ErrorCode.java
  src/main/java/bumblebee/xchangepass/global/security/SecurityConfig.java
  src/main/java/bumblebee/xchangepass/global/security/jwt/JwtAuthFilter.java
  src/main/java/bumblebee/xchangepass/global/util/EventPublisher.java
  src/test/java/bumblebee/xchangepass/domain/card/controller/CardControllerTest.java
  src/test/java/bumblebee/xchangepass/domain/card/service/CardServiceTest.java
Labels: ✨ Feature

#84 Refactor/jira kan 72 환율 및 환전 리팩토링
  src/main/java/bumblebee/xchangepass/domain/exchangeRate/service/ExchangeService.java
  src/main/java/bumblebee/xchangepass/domain/exchangeRate/util/ExchangeRateLockManager.java
  src/main/java/bumblebee/xchangepass/domain/exchangeTransaction/service/ExchangeTransactionService.java
  src/main/java/bumblebee/xchangepass/global/common/Constants.java
  src/main/java/bumblebee/xchangepass/global/config/RestTemplateConfig.java
  src/main/java/bumblebee/xchangepass/global/error/ErrorCode.java
  src/test/java/bumblebee/xchangepass/domain/exchangeRate/service/ExchangeServiceTest.java
  src/test/java/bumblebee/xchangepass/domain/exchangeRate/service/ExchangeServiceUnitTest.java
Labels: 🔨 Refactor

#85 Refactor/jira kan 71 token 쿠키 저장 및 redis aof rdb 고려
  build.gradle
  docker-compose.yml
  src/main/java/bumblebee/xchangepass/domain/card/service/CardPaymentService.java
  src/main/java/bumblebee/xchangepass/domain/refresh/controller/RefreshTokenController.java
  src/main/java/bumblebee/xchangepass/domain/refresh/dto/RefreshTokenRequest.java
  src/main/java/bumblebee/xchangepass/domain/refresh/repository/RefreshTokenRepository.java
  src/main/java/bumblebee/xchangepass/domain/refresh/service/RefreshTokenService.java
  src/main/java/bumblebee/xchangepass/domain/user/entity/User.java
  src/main/java/bumblebee/xchangepass/domain/user/login/LoginController.java
  src/main/java/bumblebee/xchangepass/domain/user/login/LoginService.java
  src/main/java/bumblebee/xchangepass/domain/user/login/dto/response/LoginResponse.java
  src/main/java/bumblebee/xchangepass/domain/user/service/UserService.java
  src/main/java/bumblebee/xchangepass/domain/wallet/balance/service/WalletBalanceService.java
  src/main/java/bumblebee/xchangepass/domain/wallet/dto/request/WalletInOutRequest.java
  src/main/java/bumblebee/xchangepass/domain/wallet/fraud/service/FraudDetectEvent.java
  src/main/java/bumblebee/xchangepass/domain/wallet/fraud/service/FraudDetectionService.java
  src/main/java/bumblebee/xchangepass/domain/wallet/fraud/service/FraudRecord.java
  src/main/java/bumblebee/xchangepass/domain/wallet/fraud/service/FraudRuleEvaluator.java
  src/main/java/bumblebee/xchangepass/domain/wallet/fraud/service/RedisFraudStorageService.java
  src/main/java/bumblebee/xchangepass/domain/wallet/service/WalletService.java
  src/main/java/bumblebee/xchangepass/domain/wallet/transaction/consumer/DeadLetterConsumer.java
  src/main/java/bumblebee/xchangepass/domain/wallet/transaction/consumer/SlackNotifier.java
  src/main/java/bumblebee/xchangepass/domain/wallet/wallet/controller/WalletController.java
  src/main/java/bumblebee/xchangepass/domain/wallet/wallet/dto/request/WalletTransferRequest.java
  src/main/java/bumblebee/xchangepass/domain/wallet/wallet/entity/ScheduledTransfer.java
  src/main/java/bumblebee/xchangepass/domain/wallet/wallet/entity/WalletTransferStatus.java
  src/main/java/bumblebee/xchangepass/domain/wallet/wallet/entity/WalletTransferType.java
  src/main/java/bumblebee/xchangepass/domain/wallet/wallet/repository/ScheduledTransferRepository.java
  src/main/java/bumblebee/xchangepass/domain/wallet/wallet/scheduler/ScheduledTransferExecutor.java
  src/main/java/bumblebee/xchangepass/domain/wallet/wallet/scheduler/ScheduledTransferService.java
  src/main/java/bumblebee/xchangepass/domain/wallet/wallet/service/impl/WalletFacadeService.java
  src/main/java/bumblebee/xchangepass/domain/wallet/wallet/service/impl/lock/NamedLockWalletService.java
  src/main/java/bumblebee/xchangepass/domain/wallet/wallet/service/impl/lock/PessimisticLockWalletService.java
  src/main/java/bumblebee/xchangepass/domain/wallet/wallet/service/impl/lock/redisson/RedissonLockWalletService.java
  src/main/java/bumblebee/xchangepass/global/security/jwt/JwtAuthFilter.java
  src/main/java/bumblebee/xchangepass/global/security/jwt/JwtProvider.java
  src/main/resources/lua/fraud_check.lua
  src/test/java/bumblebee/xchangepass/domain/user/service/UserLoginScenarioTest.java
  src/test/java/bumblebee/xchangepass/domain/user/service/UserLoginUnitTest.java
  src/test/java/bumblebee/xchangepass/domain/wallet/fraud/FraudRuleEvaluatorTest.java
  src/test/java/bumblebee/xchangepass/domain/wallet/transaction/SlackNotifierIntegrationTest.java
  src/test/java/bumblebee/xchangepass/domain/wallet/transaction/WalletTransactionIntegrationTest.java
  src/test/java/bumblebee/xchangepass/domain/wallet/wallet/service/ScheduledTransferServiceTest.java
  src/test/java/bumblebee/xchangepass/domain/wallet/wallet/service/WalletIntegrationServiceTest.java
  src/test/java/bumblebee/xchangepass/domain/wallet/wallet/service/WalletNamedLockServiceTest.java
  src/test/java/bumblebee/xchangepass/domain/wallet/wallet/service/WalletRedissonServiceTest.java
Labels: 🔨 Refactor

#89 Frontend/jira kan 86 로그인 회원가입 페이지 생성
  src/main/java/bumblebee/xchangepass/domain/user/login/LoginController.java
  src/main/java/bumblebee/xchangepass/domain/user/login/LoginService.java
  src/main/java/bumblebee/xchangepass/domain/user/repository/UserRepository.java
  src/test/java/bumblebee/xchangepass/domain/user/service/UserLoginUnitTest.java
  src/test/java/bumblebee/xchangepass/domain/wallet/wallet/service/WalletIntegrationServiceTest.java
  xcp-front/package.json
  xcp-front/src/App.vue
  xcp-front/src/api/authFetch.js
  xcp-front/src/api/userApi.js
  xcp-front/src/components/HelloWorld.vue
  xcp-front/src/components/LoginForm.vue
  xcp-front/src/components/NavBar.vue
  xcp-front/src/components/RegisterForm.vue
  xcp-front/src/components/TheWelcome.vue
  xcp-front/src/components/WelcomeItem.vue
  xcp-front/src/main.js
  xcp-front/src/router/index.js
  xcp-front/src/stores/auth.js
  xcp-front/src/views/HomeView.vue
  xcp-front/src/views/LoginView.vue
  xcp-front/src/views/RegisterView.vue
  xcp-front/vite.config.js
Labels: ✨ Feature

#91 ✨ Feat : 메인 페이지 구현 완료
  xcp-front/src/api/exchange.js
  xcp-front/src/views/HomeView.vue
  xcp-front/vite.config.js
Labels: ✨ Feature

#92 ✨ Feat : axios 추가
  result.json
  xcp-front/package-lock.json
  xcp-front/src/api/axios.js
Labels: ✨ Feature

#93 Frontend/jira kan 77 거래 페이지 생성 및 연동완료
  src/main/java/bumblebee/xchangepass/domain/exchangeRate/controller/ExchangeController.java
  src/main/java/bumblebee/xchangepass/domain/exchangeRate/repository/exchangeTemp/ExchangeRepositoryImpl.java
  src/main/java/bumblebee/xchangepass/domain/exchangeRate/service/ExchangeCacheService.java
  src/main/java/bumblebee/xchangepass/domain/wallet/wallet/controller/WalletController.java
  src/main/java/bumblebee/xchangepass/domain/wallet/wallet/dto/WalletPasswordRequest.java
  src/main/java/bumblebee/xchangepass/domain/wallet/wallet/dto/WalletPasswordResponse.java
  src/main/java/bumblebee/xchangepass/domain/wallet/wallet/dto/request/WalletTransferRequest.java
  src/main/java/bumblebee/xchangepass/domain/wallet/wallet/entity/WalletTransferType.java
  src/main/java/bumblebee/xchangepass/domain/wallet/wallet/service/impl/WalletFacadeService.java
  src/main/java/bumblebee/xchangepass/domain/wallet/wallet/service/impl/WalletServiceImpl.java
  src/main/java/bumblebee/xchangepass/domain/wallet/wallet/service/impl/lock/NamedLockWalletService.java
  src/main/java/bumblebee/xchangepass/domain/wallet/wallet/service/impl/lock/redisson/RedissonLockWalletService.java
  src/test/java/bumblebee/xchangepass/domain/wallet/wallet/service/ScheduledTransferServiceTest.java
  xcp-front/package.json
  xcp-front/src/api/authFetch.js
  xcp-front/src/api/exchange.js
  xcp-front/src/api/useExchangeCalculator.js
  xcp-front/src/components/DepositForm.vue
  xcp-front/src/components/PasswordConfirmModal.vue
  xcp-front/src/components/TransferForm.vue
  xcp-front/src/components/WithdrawForm.vue
  xcp-front/src/main.js
  xcp-front/src/router/index.js
  xcp-front/src/stores/auth.js
  xcp-front/src/views/DepositView.vue
  xcp-front/src/views/HomeView.vue
  xcp-front/src/views/TransferView.vue
  xcp-front/src/views/WithdrawView.vue
Labels: ✨ Feature

#95 Frontend/jira kan 76 메인 완료
  src/main/java/bumblebee/xchangepass/domain/exchangeTransaction/service/ExchangeTransactionService.java
  xcp-front/src/api/axios.js
  xcp-front/src/api/exchange.js
  xcp-front/src/assets/currency-name.json
  xcp-front/src/router/index.js
  xcp-front/src/views/ExchangeRateCard.vue
  xcp-front/src/views/ExchangeTransferView.vue
  xcp-front/src/views/ExchangeView.vue
  xcp-front/src/views/HomeView.vue
Labels: ✨ Feature

#96 ♻️ Refactor: fetchAndSaveExchangeRate 함수 주석 처리
  src/main/java/bumblebee/xchangepass/domain/exchangeRate/service/ExchangeService.java
  src/main/java/bumblebee/xchangepass/domain/exchangeRate/util/Country.java
Labels: 🐞 BugFix
